FROM node:14-alpine as Build
WORKDIR /app
ENV PATH=/app/node_modules/.bin:$PATH
COPY package*.json /app/
RUN npm install

FROM node:14-alpine as Test
WORKDIR /app
ENV PATH=/app/node_modules/.bin:$PATH
COPY --from=Build /app/node_modules/ /app/node_modules/
COPY . .
ENV CI=true
RUN npm test||true

FROM node:14-alpine as Delivery
WORKDIR /app
ENV PATH=/app/node_modules/.bin:$PATH
COPY --from=Build /app/node_modules/ /app/node_modules/
COPY . .
CMD ["node", "server.js"]
